### ISSUE TITLE
[Task] 개발환경 구축

### ISSUE THREAD

**Issue by alsrlqor1007** [alsrlqor1007/partyOrganizer#4]
### ISSUE
* Group: `client`, `server`
* Type: `setting`
* Detail: Node.js Express 및 React 개발 환경 구축

### TODO
- [ ] Express server Project 구축
- [ ] 서버 필요 모듈 설치
- [ ] React client Project 구축

### Estimated time
`0.5h`

### Labels
* Estimated time: `E: 0.5h`
* Group : `client`, `server`
* Urgency: `Middle`
